### ISSUE TITLE
V2.0 LUA Call Stack

### ISSUE THREAD

**Issue by hpmc13** [Slivicon/VehicleSort#4]
Thank you so much for picking up this mod and continuing with it. I wouldn't play without it. 
Unfortunately, I'm having a problem with v2.0. I get the following LUA call stack when the map is loading:
Warning (LUA): 'getXMLString': Argument 1 has wrong type. Expected: Int. Actual: Nil 
  ..\..\..\src\base\scripting\lua\LuaScriptSystem.cpp (640): expectedType == Value::VoidType
LUA call stack:
  dataS/scripts/utils/Utils.lua (1818) : getXMLString
  =E:/HGames/FS17LiveMods/FS17_VehicleSort/VehicleSort.lua (349) : getTrans
  =E:/HGames/FS17LiveMods/FS17_VehicleSort/VehicleSort.lua (810) : getName
  dataS/scripts/utils/Utils.lua (1859) : newFunc
  dataS/scripts/vehicles/Vehicle.lua (656)
  dataS/scripts/utils/Utils.lua (1858) : oldFunc
  dataS/scripts/utils/Utils.lua (1858) : oldFunc
  dataS/scripts/utils/Utils.lua (1138) : asyncCallbackFunction
It repeats about six times. The map loads and the game plays seemingly without any problems. All the functions of Vehicle Sort seem to work just fine _except_ I have "See Train Cranes" set to no. When I go through the vehicle list the cranes are not shown in the text on the screen, but when I navigate down through the list (pressing NUM-2) each vehicle will highlight, then they will stop highlighting for two presses, then the next vehicle will highlight. It's as though the list still thinks that the cranes are there but simply aren't showing them on the list. If I set cranes to visible, then park them, then set cranes to not visible everything works fine. This is in an existing savegame that used the previous version of VS. The map is Broxton. I have the Platinum Edition of FS. Broxton has two trains, one "regular" (that you drive) and one "automatic" (that you fill and then pull a handle to send off.) 

Again, thanks very much for the mod. I am happy to provide any information that you might need.

**Comment by Slivicon** [comment]
@hpmc13 Would you please try the LUA from 55e7730 to see if it fixes these issues for you?

**Comment by hpmc13** [comment]
While that seems to have fixed the LUA call stacks, there's a new error:
Error: E:/HGames/FS17LiveMods/FS17_VehicleSort/VehicleSort.lua:7: unexpected symbol near '<'
Nothing seems to work now. Pressing NUM-0 has no effect so it would appear that VS does not load - so maybe it doesn't get that far? I went back to V1.0.0.9 for the time being, but am happy to keep testing. Thanks again for all you work!

**Comment by Slivicon** [comment]
@hpmc13  Sorry about that, my rushed dev fixes this morning were not good. Please try the latest dev as of a minute ago:
https://raw.githubusercontent.com/Slivicon/VehicleSort/dev/vehicleSort.lua 
https://raw.githubusercontent.com/Slivicon/VehicleSort/dev/modDesc.xml 
Thank you for your help in testing.

**Comment by hpmc13** [comment]
Beautiful! No errors, no call-stacks. Absolutely love the changes. It certainly appears that all is well. Thanks again.
