### ISSUE TITLE
Missing name in l10n

### ISSUE THREAD

**Issue by 112tec** [Slivicon/VehicleSort#6]
I got the message on screen missing Name in l10n, but thats not correct.

Here is an example:
vehicle.xml:
...
	<storeData>
		<name>$l10n_name_BigBagFork</name>
		<specs>
...

Moddesc.xml:
...
	<l10n>
		<text name="name_BigBagFork">
			<en>UAL Big Bag fork</en>
			<de>UAL Big Bag Gabel</de>
		</text>
		<text name="WORKMODE_on">
...

**Comment by Slivicon** [comment]
Would you please give me a link to this mod for the big bag so I can see and test.

**Comment by Slivicon** [comment]
@112tec I've restored some of the previous version of the function to read the xml for vehicles - it may help with mods that do not format the xml the same way and might resolve this. If you provide a link to the mod for UAL Big Bag and the version you are using I can try to download it to test.
https://raw.githubusercontent.com/Slivicon/VehicleSort/dev/vehicleSort.lua 
https://raw.githubusercontent.com/Slivicon/VehicleSort/dev/modDesc.xml

**Comment by 112tec** [comment]
http://filehorst.de/d/cpgbychh

**Comment by Slivicon** [comment]
@112tec thank you, I was able to test an update to get it to work. Please try again with the latest DEV files in your zip:
https://raw.githubusercontent.com/Slivicon/VehicleSort/dev/vehicleSort.lua
https://raw.githubusercontent.com/Slivicon/VehicleSort/dev/modDesc.xml

**Comment by 112tec** [comment]
Thank you Slivicon! 

Version 2.1.0.0 works perfect for me! 

All issues solved! Great Job!
